config:
  project_name: some-rails-project
  image: alpine

#services:
#  - mssql

steps:
  build:
    - echo "Hello World!"
    - ls -lt
  test:
    - echo "Testing hello World!"
    - ls -lt

timeout: 600

